### PR TITLE
Circle cards component

### LINKED ISSUE #64: Design System Component: Circle Buttons
### Dependency

- [ ] #48
- [ ] #62 

### Overview
As a developer, we should start with a component first philosophy when creating new webpages. For this issue we will be developing the circle buttons of the Landing Page.

### Action Items

- [ ] Review the design for the circle button element in the landing page in the Figma page indicated below (they are the circles containing the CoPs)
- [ ] Be sure to review our architecture documentation to understanding where to create and find files relevant to this component
- [ ] Make sure that the component is:
  - [ ] Responsive, and that the items adjust themselves as screen size changes
  - [ ] Change from the desktop to mobile design after the mobile breakpoint

### Resources/Instructions
[Figma, Landing Page](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A7)

### PR DESCRIPTION
**Pull request by Aveline-art**
Fixes #64

### Changes

- created circle card component, which has "sm" or "lg" choices for the size prop
- cleaned up some imports from `InnerCopNav.js`
- updated Demo page to showcase usage of new component
- created responsive mixin for circle card

### CODE REVIEW

**Comment by Aveline-art** [comment]
@NickTSA Hey, I know you're going to be on vacay, and I don't want this to be on hold for too long. Let me know if you would like to review this by Tuesday, or I will merge this on my discretion.

**Comment by NickTSA** [comment]
Yes, I’ll try to review it as soon as I can

**Comment by NickTSA** [comment]
Everything looks good. Only item I noticed is the title on the circle cards. Desktop should be _title 4_ and mobile _title 6_ .

**Comment by Aveline-art** [comment]
Good catch. I've created a responsive class so that we can address the need to responsively shrink down the card. Unfortunately, for the content, such as the image and the title, it will have to shrink through manually created breakpoint classes, which I am slightly unhappy about.

**Comment by Aveline-art** [comment]
@NickTSA Feel free to review this again. Since I want to be on track to finish our goals for the month, I will merge this tonight as I am pretty satisfied with it.

**Review by NickTSA — APPROVED** [review]
looks good to me! 👍

**Pull request merged**
