### PR TITLE
Designed buttons in React

### LINKED ISSUE #61: Design System Components: Buttons
### Dependency

- [ ] Architecture Doc
- [ ] Colors

### Overview
As a developer, we should start with a component first philosophy when creating new webpages. For this issue we will be developing the buttons of the Landing Page.

### Action Items

- [ ] Review the design for the button element in the landing page in the Figma page indicated below
- [ ] Be sure to review our architecture documentation to understanding where to create and find files relevant to this component
- [ ] Make sure that the component is:
  - [ ] Responsive, and that the items adjust themselves as screen size changes
  - [ ] Change from the desktop to mobile design after the mobile breakpoint

### Resources/Instructions
[Figma, Landing Page](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A7)

### PR DESCRIPTION
**Pull request by Aveline-art**
Fixes #61

### Changes

- Added `breakpoint-media-max` mixin which uses max-width in order to make desktop first responsiveness clases
- Added new color variables for button states
- Changed typography to mixins to account for [media @extend errors](https://stackoverflow.com/a/14841491)
- Created `<Button />` react component featuring
  - conditionally render tags based on the addition of `href` props
  - [`propsType`](https://reactjs.org/docs/typechecking-with-proptypes.html) library to type-check inserted props and soft-catch errors
  - helper function to efficiently create a class string from multiple props
  - a spillover `class` prop for any custom class or override classes, such as classes to add margins or padding, or adding responsiveness
- Created button mixins and classes, including:
  - `.btn` class for all button properties
  - `button-size` mixin for buttons of different size, including variations
  - `button-length` mixin that, for now, only increases the border padding of the button
  - `button-theme` mixin for various colors themes and color changes due to button states (disabled, hover, active, etc)
  - `button-responsive` mixin that can create responsive classes based on max-width breakpoints
- Updated frontpage demo to showcase the various classes and their usage to aid review

### Screenshots, if applicable

No screenshots, but developer's note: Oh my goodness, this issue was brutal!

### CODE REVIEW

**Comment by Aveline-art** [comment]
@jenchuu I have added [new color variables with their names](frontend/src/components/Basics/_colors.scss). I know the designers use gradients, and I would love to know more about that so that developers can more sensible calculate color variables. Nevertheless, please take a look and let me know if you agree with the names I've used and if it works for you team.

**Comment by jenchuu** [comment]
> 

Colors look good so far! One thing: can we move $white: #FFFFFF to NEUTRAL color class?
and noting our discussion change of the blue button to being Primary on dark instead of Secondary button.

**Comment by Aveline-art** [comment]
Converting this to draft because I just realized that size and length can be intelligently separated, because "regular" to "long" variations is exactly 16px independent of size.

**Comment by Aveline-art** [comment]
Merging this because it is officially finished

**Pull request merged**
