### PR TITLE
Issuse175

### LINKED ISSUE #175: Split Cards into Multiple Components
### Overview

As a developer we need to keep our codebase clean by keeping a one file per component rule. For this issue we will separate out our cards into different files so that they are easier to find.

### Action Items

- [ ] Find the components in the specified file below.
- [ ] Split the components into different files, both js and scss, named after the components
- [ ] Make sure that the website still runs by fixing all imports and any other errors that arise.
- [ ] Since this is a refactor, the website's appearance should not change.

### Resources/Instructions

[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)
[Cards.js](https://github.com/hackforla/CivicTechJobs/blob/main/app/frontend/src/components/Cards/Cards.js)
[_Cards.scss](https://github.com/hackforla/CivicTechJobs/blob/main/app/frontend/src/components/Cards/_Cards.scss)

### PR DESCRIPTION
**Pull request by poorvarathore05**
Fixes #175 

### Changes
Split the function into multiple components and followed the Scss file

### CODE REVIEW

**Comment by Aveline-art** [comment]
@poorvarathore05 Is there an update on this?

**Comment by poorvarathore05** [comment]
@Aveline-art 
Hello Ava,

What visuals got changed I didn't make any other changes other than creating the new components and I don't know why the Lint test is failing.

**Comment by Aveline-art** [comment]
@poorvarathore05 When viewing the homepage, the popup dialog on the front page did not correctly receive the css styles. You will see a difference when you view the site from the dev-branch-1 and your current branch.

**Review by Aveline-art — CHANGES_REQUESTED** [review]
Everything looks good. Let's rename the `Cards.*` files after the component inside of it as well and this can be merged.

**Pull request merged**
