### PR TITLE
lint ignore stage Dockerfile

### PR DESCRIPTION
**Pull request by Enzyme3**
### Changes
- Pin python alpine image to specific version

### CODE REVIEW

**Comment by Aveline-art** [comment]
Just a quick question. Why pin curl to the specific version? I doubt curl will break based on how we are using it, but we do want to migrate to major python versions periodically to ensure repository freshness and patch core code bugs.

**Comment by Enzyme3** [comment]
honestly, it's because the linter complains. If wanted, can add an exclusion rule for those two lines

**Comment by Aveline-art** [comment]
@Enzyme3 Let's do an inclusion filter, and make sure that deployment does not happen if this fails (which it should, since docker failed).

**Review by Aveline-art — APPROVED** [review]
Looks good!

**Pull request merged**
