### PR TITLE
Scroll

### PR DESCRIPTION
**Pull request by gjagnoor**
#341 

Please review this PR for functionality. I will clean up the code next. Please review the code in the next PR. 

scroll

### CODE REVIEW

**Comment by gjagnoor** [comment]
@Aveline-art Is the Chip component you were working on ready to be used? I would like to use it for this component if that's ok with you. The chips you see in the gif attached are something I quickly put together to keep this feature work going. I'd rather replace these with your version to cut down on redundancy if we are ready to do so.

**Comment by Aveline-art** [comment]
@gjagnoor The chip is merged already, so you can use it at your leisure. That said, it does not look like those are chip components, since they do not follow the rough specs in the design system.

Let me check in with the design team and get back on this.

**Review by Aveline-art — CHANGES_REQUESTED** [review]
Functionally, it is missing two things:

- It's not scrollable by mouse wheel, for some reason. Looking at the code, I can't really tell why, since it's a div overflow at a glance.
- The scroll is too slow, so it's not usable at all. It also does not snap at the next children. Is there a reason why a custom scroll is used rather than something like `scroll-snap-stop`?

**Comment by Aveline-art** [comment]
@gjagnoor Thank you for you work on this. As there has not been activity, I will close the ticket and throw it back into the backlog. Thank you!

**Pull request closed without merging**
